import { cn } from '@/lib/utils'
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import NavBar from '@/components/navbar'

const opensans = Open_Sans({ subsets: ['hebrew'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: { 
  children: React.ReactNode
}) {
  return (
    <html lang="he" dir="rtl">
      <body className={cn(opensans.className, "overflow-visible flex flex-col items-center min-h-screen")}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}